name: HTML Linting
on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "package*.json"
      - ".htmlhintrc"
      - ".vnurc"
      - "aria-practices.html"
      - "examples/**/*.html"
      - ".github/workflows/lint-html.yml"
      - ".github/workflows/vnu-jar-problem-matcher.json"
      - ".github/workflows/htmlhint-problem-matcher.json"

  pull_request:
    paths:
      - "package*.json"
      - ".htmlhintrc"
      - ".vnurc"
      - "aria-practices.html"
      - "examples/**/*.html"
      - ".github/workflows/lint-html.yml"
      - ".github/workflows/vnu-jar-problem-matcher.json"
      - ".github/workflows/htmlhint-problem-matcher.json"

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4

      - name: Install npm dependencies
        run: npm ci

      - name: HTML Validator
        run: |
          echo "::add-matcher::.github/workflows/vnu-jar-problem-matcher.json"
          echo "::add-matcher::.github/workflows/htmlhint-problem-matcher.json"
          npm run lint:html
