name: Trigger pull request creation for wai repository

on:
  pull_request:
    paths:
      - ".github/workflows/wai-trigger-pr.yml"
      - "package*.json"
      - "test/**"
      - "examples/**"
      - "!examples/landmarks/**"
      - "!examples/coding-template/**"
      - "README.md"

jobs:
  create-pr-wai:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Run wai-trigger-pr script
        run: |
          node scripts/wai-trigger-pr.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APG_BRANCH: ${{ github.head_ref }}
          APG_SHA: ${{ github.event.pull_request.head.sha }}
          APG_PR_NUMBER: ${{ github.event.pull_request.number }}
