name: Trigger PR update for WAI-APG site

on:
  pull_request_target:
    branches-ignore:
      - "dependabot/**"
    paths:
      - ".github/workflows/wai-trigger-pr.yml"
      - ".github/workflows/regression.yml"
      - ".github/workflows/examples.yml"
      - "scripts/reference-tables.*"
      - "**/*.js"
      - "test/**"
      - "examples/**"
      - "aria-practices.html"
      - "index.html"
      - "!examples/landmarks/**"
      - "!examples/coding-template/**"
      - "!common/**"

jobs:
  create-pr-wai:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Trigger wai-aria-practices PR update
        uses: actions/github-script@v5
        env:
          APG_BRANCH: ${{ github.head_ref }}
          APG_SHA: ${{ github.event.pull_request.head.sha }}
          APG_PR_NUMBER: ${{ github.event.pull_request.number }}
          FORK_PATH: ${{ github.event.pull_request.head.repo.fork && github.event.pull_request.head.repo.full_name }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'wai-aria-practices',
              workflow_id: 'pr-create.yml',
              ref: 'main',
              inputs: {
                apg_branch: process.env.APG_BRANCH,
                apg_sha: process.env.APG_SHA,
                apg_pr_number: process.env.APG_PR_NUMBER,
                fork_path: process.env.FORK_PATH,
              }
            });
